.PHONY: clean All

All:
	@echo "----------Building project:[ bank - Debug ]----------"
	@$(MAKE) -f  "bank.mk"
clean:
	@echo "----------Cleaning project:[ bank - Debug ]----------"
	@$(MAKE) -f  "bank.mk" clean
